addprinc -pw lle hdfs
ktadd -k ./output/kerberos/hdfs.keytab hdfs
addprinc -pw lle hive
ktadd -k ./output/kerberos/hive.keytab hive
addprinc -pw lle impala
ktadd -k ./output/kerberos/impala.keytab impala
addprinc -pw lle hbase
ktadd -k ./output/kerberos/hbase.keytab hbase
addprinc -pw lle sentry
ktadd -k ./output/kerberos/sentry.keytab sentry
