version: 1
formatters:
  brief:
    format: '%(levelname)-8s: %(name)-15s: %(message)s'
  precise:
    format: '%(asctime)s %(filename)s[line:%(lineno)d] %(levelname)s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    formatter: brief
    level: INFO
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: precise
    filename: slk.log
    mode: a
  debugFile:
    class: logging.FileHandler
    formatter: precise
    filename: slk-detail.log
    mode: a

loggers:
  console:
    level : INFO
    handlers: [console]
  file:
    level: INFO
    handlers: [console, file]
    propagate: no
  debugFile:
    level: DEBUG
    handlers: [console, debugFile]

root:
  level: DEBUG
  handlers: [console, file, debugFile]