---
- name: install cloudera manager packages
  yum:
    name: "{{ packages }}"
    state: present
    vars:
      packages:
        - "{{ pkg_cm_daemons }}"
        - "{{ pkg_cm_server }}"
        - psmisc

- name: copy file, db init script
  copy:
    src: file/init.sql
    dest: /tmp/init.sql

- name: init cdh required databases environments
  shell: mysql -h{{ mysql_host }} -u{{ mysql_user }} -p{{ mysql_password }} < /tmp/init.sql
  args:
    executable: /bin/bash

- name: execute /usr/share/cmf/schema/scm_prepare_database.sh
  command: usr/share/cmf/schema/scm_prepare_database.sh -h{{ mysql_host }} -u{{ mysql_user }} -p{{ mysql_password }} --scm-host {{ cm_host }} mysql cmf cmf Uydc.cmf
  notify:
    - echo uptime

- name: enable and start cloudera manager
  systemd:
    name: "{{ svc_cm_server }}" 
    state: started
