---
- name: install cloudera manager packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - psmisc
      - "{{ pkg_cm_daemons }}"
      - "{{ pkg_cm_server }}"

- name: copy file, db init script
  copy:
    src: files/init.sql
    dest: /tmp/init.sql

- name: init cdh required databases environments
  shell: mysql -h{{ mysql_host }} -u{{ mysql_user }} -p{{ mysql_password }} < /tmp/init.sql
  args:
    executable: /bin/bash

- name: execute {{ scm_prepare_database_sh }}
  command: "{{ scm_prepare_database_sh }} -h{{ mysql_host }} -u{{ mysql_user }} -p{{ mysql_password }} --scm-host {{ cm_host }} mysql cmf cmf Uydc.cmf"
  notify:
    - echo uptime

- name: enable and start cloudera manager
  systemd:
    name: "{{ svc_cm_server }}" 
    state: started
