- name: install cloudera manager agent
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - psmisc
      - "{{ pkg_cm_agent }}"
  

# - name: parted data partion
#   command: "{{ item }}"
#   with_items:
#     - dd if=/dev/zero of=/dev/sdb bs=512 count=1
#     - parted /dev/sdb mklabel gpt
#     - parted -a optimal /dev/sdb mkpart primary 0% 100%
#     - parted /dev/sdb print
#     - mkfs.xfs /dev/sdb1