"kadmin -p root/admin -w Uydc.2910 ktadd -k /Users/lilongen/github/cdh-on-centos/kerberos+sentry+ldap/keytab//lile.keytab\n\
kadmin -p root/admin -w Uydc.2910 ktadd -k /Users/lilongen/github/cdh-on-centos/kerberos+sentry+ldap/keytab//wangjd.keytab\n\
kadmin -p root/admin -w Uydc.2910 ktadd -k /Users/lilongen/github/cdh-on-centos/kerberos+sentry+ldap/keytab//luoyw.keytab\n\
kadmin -p root/admin -w Uydc.2910 ktadd -k /Users/lilongen/github/cdh-on-centos/kerberos+sentry+ldap/keytab//baosy.keytab\n\
kadmin -p root/admin -w Uydc.2910 ktadd -k /Users/lilongen/github/cdh-on-centos/kerberos+sentry+ldap/keytab//liuzl.keytab\n\
kadmin -p root/admin -w Uydc.2910 ktadd -k /Users/lilongen/github/cdh-on-centos/kerberos+sentry+ldap/keytab//wanglj.keytab\n\
kadmin -p root/admin -w Uydc.2910 ktadd -k /Users/lilongen/github/cdh-on-centos/kerberos+sentry+ldap/keytab//guoqp.keytab\n\
kadmin -p root/admin -w Uydc.2910 ktadd -k /Users/lilongen/github/cdh-on-centos/kerberos+sentry+ldap/keytab//liukl.keytab\n\
kadmin -p root/admin -w Uydc.2910 ktadd -k /Users/lilongen/github/cdh-on-centos/kerberos+sentry+ldap/keytab//tangzx.keytab\n\
kadmin -p root/admin -w Uydc.2910 ktadd -k /Users/lilongen/github/cdh-on-centos/kerberos+sentry+ldap/keytab//maocy.keytab\n\
kadmin -p root/admin -w Uydc.2910 ktadd -k /Users/lilongen/github/cdh-on-centos/kerberos+sentry+ldap/keytab//wangxt.keytab\n\
kadmin -p root/admin -w Uydc.2910 ktadd -k /Users/lilongen/github/cdh-on-centos/kerberos+sentry+ldap/keytab//zhyu.keytab\n\
kadmin -p root/admin -w Uydc.2910 ktadd -k /Users/lilongen/github/cdh-on-centos/kerberos+sentry+ldap/keytab//jingwz.keytab\n\
kadmin -p root/admin -w Uydc.2910 ktadd -k /Users/lilongen/github/cdh-on-centos/kerberos+sentry+ldap/keytab//xuxt.keytab\n\
kadmin -p root/admin -w Uydc.2910 ktadd -k /Users/lilongen/github/cdh-on-centos/kerberos+sentry+ldap/keytab//liuc.keytab\n\
kadmin -p root/admin -w Uydc.2910 ktadd -k /Users/lilongen/github/cdh-on-centos/kerberos+sentry+ldap/keytab//yujun.keytab\n\
kadmin -p root/admin -w Uydc.2910 ktadd -k /Users/lilongen/github/cdh-on-centos/kerberos+sentry+ldap/keytab//sunxf.keytab\n\
kadmin -p root/admin -w Uydc.2910 ktadd -k /Users/lilongen/github/cdh-on-centos/kerberos+sentry+ldap/keytab//suxj.keytab\n\
kadmin -p root/admin -w Uydc.2910 ktadd -k /Users/lilongen/github/cdh-on-centos/kerberos+sentry+ldap/keytab//yangwb.keytab\n\
kadmin -p root/admin -w Uydc.2910 ktadd -k /Users/lilongen/github/cdh-on-centos/kerberos+sentry+ldap/keytab//yyc.keytab\n\
kadmin -p root/admin -w Uydc.2910 ktadd -k /Users/lilongen/github/cdh-on-centos/kerberos+sentry+ldap/keytab//prt.keytab\n\
kadmin -p root/admin -w Uydc.2910 ktadd -k /Users/lilongen/github/cdh-on-centos/kerberos+sentry+ldap/keytab//pol.keytab\n"
