---
- name: clean uninstall cdh.cm.server
  hosts: cm
  remote_user: root
  # remote_user: user
  # become: yes
  # become_method: sudo

  roles:
    - cm

- name: clean uninstall cdh.cm.agent
  hosts: node
  remote_user: root
  # remote_user: user
  # become: yes
  # become_method: sudo

  roles:
    - common